// Generated by scripts/generate-assets.mjs. Run npm.cmd run assets after adding media.
import sound_0 from "./__generated_sounds/hot-streak/01-Deep_male_voice_excl__2-1778213426184.wav?url";
import sound_1 from "./__generated_sounds/hot-streak/02-Deep_male_voice_excl__3-1778213436712.wav?url";
import sound_2 from "./__generated_sounds/hot-streak/03-Deep_male_voice_excl__4-1778213445900.wav?url";
import sound_3 from "./__generated_sounds/hot-streak/04-Playful_video_game_a__1-1778213078304.wav?url";
import sound_4 from "./__generated_sounds/hot-streak/05-Playful_video_game_a__1-1778213321661.wav?url";
import sound_5 from "./__generated_sounds/hot-streak/06-Playful_video_game_a__2-1778213140595.wav?url";
import sound_6 from "./__generated_sounds/hot-streak/07-Playful_video_game_a__2-1778213330429.wav?url";
import sound_7 from "./__generated_sounds/hot-streak/08-Playful_video_game_a__3-1778213340244.wav?url";
import sound_8 from "./__generated_sounds/hot-streak/09-Playful_video_game_a__4-1778213159382.wav?url";
import sound_9 from "./__generated_sounds/hot-streak/10-Playful_video_game_a__4-1778213356718.wav?url";
import sound_10 from "./__generated_sounds/potato-explode/01-Massive__cartoonish___1-1778215245674.wav?url";
import sound_11 from "./__generated_sounds/potato-explode/02-Massive__cartoonish___1-1778215850865.wav?url";
import sound_12 from "./__generated_sounds/potato-explode/03-Massive__cartoonish___2-1778215237607.wav?url";
import sound_13 from "./__generated_sounds/potato-explode/04-Massive__cartoonish___2-1778215857118.wav?url";
import sound_14 from "./__generated_sounds/potato-explode/05-Massive__cartoonish___3-1778215229111.wav?url";
import sound_15 from "./__generated_sounds/potato-explode/06-Massive__cartoonish___3-1778215866883.wav?url";
import sound_16 from "./__generated_sounds/potato-explode/07-Massive__cartoonish___4-1778215217702.wav?url";
import sound_17 from "./__generated_sounds/potato-explode/08-Massive__cartoonish___4-1778215874022.wav?url";
import sound_18 from "./__generated_sounds/baby-voice/01-Deep__gravelly_NPC_v__1-1778279025046.wav?url";
import sound_19 from "./__generated_sounds/baby-voice/02-Deep__gravelly_NPC_v__1-1778279123741.wav?url";
import sound_20 from "./__generated_sounds/baby-voice/03-Deep__gravelly_NPC_v__2-1778279113671.wav?url";
import sound_21 from "./__generated_sounds/baby-cry/01-A_cartoon_baby_cryin__2-1778278793120.wav?url";
import sound_22 from "./__generated_sounds/baby-cry/02-Retro_arcade_game_wa__1-1778278852530.wav?url";
import sound_23 from "./__generated_sounds/scary/01-Shephard_tone__1-1778218019228.wav?url";
import sound_24 from "./__generated_sounds/scary/02-Shephard_tone__2-1778218044860.wav?url";
import sound_25 from "./__generated_sounds/scary/03-Shephard_tone__3-1778218056253.wav?url";
import sound_26 from "./__generated_sounds/scary/04-Shephard_tone__4-1778218065145.wav?url";
import sound_27 from "./__generated_sounds/root/01-A_lot_of_spud.wav?url";

const manifest = {
  "avatars": [
    "avatar-flute-sprout.png",
    "avatar-fork-friend.png",
    "avatar-harvest-hero.png",
    "avatar-moss-sage.png",
    "avatar-paint-pal.png",
    "avatar-soup-chef.png",
    "avatar-spike-guard.png",
    "avatar-spud-king.png",
    "avatar-tater-runner.png",
    "avatar-trail-scout.png"
  ],
  "potatoFiles": [
    "2fc92bf1-5242-451d-abf4-15bc120e9b2d (1).png",
    "2fc92bf1-5242-451d-abf4-15bc120e9b2d.png",
    "4b656750-c5cd-4770-878b-40b4f4f34729.png",
    "9cf49c71-8422-4971-8dfa-657cc85f6ce6.png",
    "21bb252d-7af3-496b-a597-52c48360d5b6.png",
    "34c503af-22ef-4fd3-8338-d62746bb68ed.png",
    "72f24634-eca3-49d6-a21c-c949d10115f0.png",
    "83d78d0e-28ea-4b21-8d54-4b6e600b115e.png",
    "705a2a47-69be-44a7-b804-6e9957812cee.png",
    "858f21c3-1e37-4b05-ac8a-aa7dd8ef5079.png",
    "a3df9978-8a4c-445c-b208-875081004bd3.png",
    "cb6fb45c-d71e-4dac-a6b7-446a36abee18.png",
    "e636bb14-19ed-4740-b6c4-bbdbeadf8823.png"
  ],
  "adFiles": [
    "mp_.mp4",
    "ooh_that_s_awesome_but_where_i.mp4",
    "Sock_Puppets.mp4"
  ],
  "sounds": {
    "hotStreak": [
      sound_0,
      sound_1,
      sound_2,
      sound_3,
      sound_4,
      sound_5,
      sound_6,
      sound_7,
      sound_8,
      sound_9
    ],
    "potatoExplode": [
      sound_10,
      sound_11,
      sound_12,
      sound_13,
      sound_14,
      sound_15,
      sound_16,
      sound_17
    ],
    "babyVoice": [
      sound_18,
      sound_19,
      sound_20
    ],
    "babyCry": [
      sound_21,
      sound_22
    ],
    "scary": [
      sound_23,
      sound_24,
      sound_25,
      sound_26
    ],
    "aLotOfSpud": [
      sound_27
    ]
  }
};

export default manifest;
